### ISSUE TITLE
Copy, move and assignment ctor

### ISSUE THREAD

**Issue by svgsponer** [s-yata/darts-clone#2]
Hi, 

I just wanted to ask if there is a specific reason that I don't see to disallow the copy and assignment operator or are they just not implemented?

Thanks and best wishes, 
Severin

**Comment by s-yata** [comment]
Do you want to ask the reason why DoubleArrayImpl disallows the copy and assignment operator?

It is because DoubleArrayImpl does not require the copy and assignment operator.

**Comment by svgsponer** [comment]
Yes exactly, sorry I wasn't very precise with my question.
Do I understand you right that we don't need these operators since there only should exist one copy of the DoubleArray?
I ask because I run in some problem if I use DoubleArray as a members in a class which I want to initialize with another DoubleArray but I think i found a solution with pointers.
Thank you anyway.
